sudo: false
addons:
  apt:
    sources:
    - chef-current-precise
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
before_script:
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- "/opt/chefdk/embedded/bin/chef gem install chef-sugar"
script:
- "/opt/chefdk/embedded/bin/chef --version"
# - "/opt/chefdk/embedded/bin/rubocop --version"
# - "/opt/chefdk/embedded/bin/rubocop"
- "/opt/chefdk/embedded/bin/foodcritic --version"
- "/opt/chefdk/embedded/bin/foodcritic . --exclude spec"
- "/opt/chefdk/embedded/bin/rspec spec"
before_deploy:
- openssl enc -d -aes-256-cbc -k $CHEF_KEY -in .travis/publish-key.pem.enc -out .travis/publish-key.pem
deploy:
  edge: true
  provider: chef-supermarket
  user_id: erichelgeson
  client_key: ".travis/publish-key.pem"
  cookbook_category: Other
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: B1nEA+NyDI7eL/h34ozPUVoKAxFxUkc72Lar3mO3SZ9lq5I0Ai1WyYSLmrspYnutq/HASpGLDmf8qidlEbyVXgD7ptm6ovPcT0AZq27xTUvEKqGpRZJ3bg+YKGyTKQDpuCRjddFO8zdc936udSMtwk/ughiTq8MhOqCtSPJBcsk=
