---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.3.0

provisioner:
  name: chef_solo
  cookbook_files_glob: "**/*"

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: chef/ubuntu-12.04
  - name: ubuntu-14.04
    driver_config:
      box: chef/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[magic::test]
    attributes: {}