name 'learn_chef'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn_chef'
long_description 'Installs/Configures learn_chef'
version '0.1.0'
