name             "Notepadplus_2"
maintainer        "Akshara Technlogies"
maintainer_email  "saidulu.alli@gmail.com"
license           "Apache 2.0"
license          "All rights reserved"
description      "Installs/Configures Notepad++"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0.4"
supports         "windows"
depends          "windows"
