source 'http://rubygems.org'

gem 'chefspec'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'chef', '>= 15.4.45'
gem 'foodcritic'
gem 'rubocop', '>= 0.49.0'
gem 'rake', '>= 12.3.3'
gem 'berkshelf', '>= 4.2.3'
